version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: modclean
    main: ./cmd/modclean
    binary: modclean
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }}"
  - id: modup
    main: ./cmd/modup
    binary: modup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }}"
  - id: sortimports
    main: ./cmd/sortimports
    binary: sortimports
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }}"

archives:
  - ids: [modup, sortimports]
    formats: [binary]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
