version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/modup
    id: modup
    binary: modup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }}"
  - main: ./cmd/sortimports
    id: sortimports
    binary: sortimports
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{ .Version }}"

archives:
  - formats: [binary]
    builds:
      - modup
      - sortimports

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
